config/routes.rb
Rails.application.routes.draw do

  root "stocks#index"

  resources :stocks do
    collection do
      get "csv"
    end
  end
  resources :error_logs, only: [:index]

end

app/models/error_log.rb
class ErrorLog < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  validates :code, presence: true, numericality: { only_integer: true }
  validates :date, presence: true
  validates :adjusted_closing_price, numericality: true, allow_blank: true
  validates :empty_corrected_price, numericality: true, allow_blank: true

  def prev_price
    prev_stock = Stock.find_by(code: code, date: TradingDayJp.prev(date))
    prev_stock.adjusted_closing_price || prev_stock.empty_corrected_price if prev_stock.present?
  end

  def self.find_or_create(attrs)
    find_by(code: attrs[:code], date: attrs[:date]).presence || create(attrs)
  end

  def self.update_or_create(attrs)
    if stock = find_by(code: attrs[:code], date: attrs[:date])
      stock.update(attrs)
    else
      create(attrs)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/error_logs_controller.rb
class ErrorLogsController < ApplicationController

  def index
    @error_logs = ErrorLog.order(id: :desc).page(params[:page])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    @stocks = StockForm.new(params).result.page(params[:page]) if params[:matrix].blank?
    @rows = Kaminari.paginate_array(StockForm.new(params).matrix_result).page(params[:page]) if params[:matrix].present?
  end

  def new
  end

  def create
    if stocks_params[:codes].blank?
      render :new
    else
      stocks_params[:codes].lines.each do |code|
        params = { start_at: stocks_params[:start_at], end_at: stocks_params[:end_at], code: code.chomp }
        YahooCrawler.perform_now(params)
      end
      redirect_to stocks_path, notice: "株価を新規取得しました。"
    end
  end

  def csv
    if params[:matrix].blank?
      @stocks = StockForm.new(params).result
      generated_csv = CSV.generate do |csv|
        csv << %w(証券コード 日付 調整後終値)
        @stocks.find_each do |stock|
          stock_price = if params[:empty_correction]
            stock.update(empty_corrected_price: stock.prev_price) if stock.adjusted_closing_price.blank? && stock.empty_corrected_price.blank?
            stock.adjusted_closing_price || stock.empty_corrected_price
          else
            stock.adjusted_closing_price
          end
          csv << [
            stock.code,
            stock.date,
            stock_price
          ]
        end
      end
      send_data(generated_csv.encode(Encoding::CP932, invalid: :replace, undef: :replace), filename: "stocks.csv", type: "text/csv; charset=shift_jis")
    else
      @rows = StockForm.new(params).matrix_result
      generated_csv = CSV.generate do |csv|
        codes = @rows.first.map{ |content| content[:code].to_s }
        codes = codes.unshift("")
        csv << codes
        @rows.each do |row|
          array = [row.first[:date]]
          row.each do |content|
            stock = Stock.find_by(code: content[:code], date: content[:date])
            if stock.blank?
              array << [""]
            else
              array << if params[:empty_correction]
                stock.adjusted_closing_price || stock.empty_corrected_price
              else
                stock.adjusted_closing_price
              end
            end
          end
          csv << array
        end
      end
      send_data(generated_csv.encode(Encoding::CP932, invalid: :replace, undef: :replace), filename: "stocks.csv", type: "text/csv; charset=shift_jis", disposition: "attachment")
    end
  end

  private

  def stocks_params
    params.permit(:start_at, :end_at, :codes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_logs_helper.rb
module ErrorLogsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/error_logs/index.html.slim
h1 エラーログ
br
= paginate @error_logs
table.table.table-hover
  thead
    tr
      th 日時
      th params
      th error
  tbody
    - @error_logs.each do |error_log|
      tr
        td
          = error_log.created_at
        td
          = error_log.params
        td
          = error_log.error
= paginate @error_logs      

app/views/layouts/_footer.html.slim
.footer
  .container
    .copyright
      Copyright &copy; 2016 Ken Mitamura All Rights Reserved.

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      = link_to "株価データ取得サービス", root_path, id: "logo", class: "navbar-brand", style: "color:white;"
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-left
        li
          = link_to "新規取得", new_stock_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tstock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/stocks/index.html.slim
h1 株価一覧
br
.well
  = form_tag(stocks_path, method: :get) do
    .row
      .col-xs-2.text-center
        | 期間
      .col-xs-4
        = date_field_tag :start_at, params[:start_at], class: "form-control"
      .col-xs-2.text-center
        | 〜
      .col-xs-4
        = date_field_tag :end_at, params[:end_at], class: "form-control"
    .row
      .col-xs-2.text-center
        | 証券コード
      .col-xs-4
        = text_area_tag :codes, params[:codes], class: "form-control", placeholder: "0000\r\n1111\r\n2222\r\n3333\r\n4444\r\n5555", rows: 6
    .row
      .col-xs-2.text-center
        | 空欄補正
      .col-xs-1
        = check_box_tag :empty_correction, true, params[:empty_correction]
      .col-xs-9
        | (証券取引所運営日に該当する日の株価データが存在しない場合、前日のデータを挿入します。)
    .row
      .col-xs-2.text-center
        | 複数列表示
      .col-xs-1
        = check_box_tag :matrix, true, params[:matrix]
      .col-xs-9
        | (日付を縦軸、証券コードを横軸として行列形式で表示します。)
    .row
      .col-xs-2.text-center
        |並び替え
      .col-xs-4
        = select_tag :sort, options_for_select({"---": "", "証券コード昇順：日付昇順": 1, "証券コード昇順：日付降順": 2, "証券コード降順：日付昇順": 3, "証券コード降順：日付降順": 4}, selected: params[:sort]), class: "form-control"
    .row
      button.btn.btn-primary.col-xs-offset-5.col-xs-2 type="submit"
        | 検索
.pull-right
  = link_to "現在の条件でCSVダウンロード", csv_stocks_path(params), class: "btn btn-warning"
- if params[:matrix]
  = paginate @rows
  table.table.table-hover
    thead
      tr
        th
        - codes = @rows.first.map{ |content| content[:code] }
        - codes.each do |code|
          th
            = code
    tbody
      - @rows.each do |row|
        tr
          td
            strong
              = row.first[:date]
          - row.each do |content|
            td
              - stock = Stock.find_by(code: content[:code], date: content[:date])
              - if stock.blank?
              - elsif params[:empty_correction]
                = stock.adjusted_closing_price || stock.empty_corrected_price
              - else
                = stock.adjusted_closing_price
  = paginate @rows
- else
  = paginate @stocks
  table.table.table-hover
    thead
      tr
        th 証券コード
        th 日付
        th 調整後終値
    tbody
      - @stocks.each do |stock|
        tr
          td
            = stock.code
          td
            = stock.date
          td
            - if params[:empty_correction]
              - stock.update(empty_corrected_price: stock.prev_price) if stock.adjusted_closing_price.blank? && stock.empty_corrected_price.blank?
              = stock.adjusted_closing_price || stock.empty_corrected_price
            - else
              = stock.adjusted_closing_price
  = paginate @stocks

app/views/stocks/new.html.slim
h1 株価新規取得
br
.well
  = form_tag(stocks_path, method: :post) do
    .row
      .col-xs-2.text-center
        | 期間
      .col-xs-4
        = date_field_tag :start_at, params[:start_at], class: "form-control"
      .col-xs-2.text-center
        | 〜
      .col-xs-4
        = date_field_tag :end_at, params[:end_at], class: "form-control"
    .row
      .col-xs-2.text-center
        | 証券コード
      .col-xs-4
        = text_area_tag :codes, params[:codes], class: "form-control", placeholder: "0000\r\n1111\r\n2222\r\n3333\r\n4444\r\n5555", rows: 6
    .row
      button.btn.btn-primary.col-xs-offset-5.col-xs-2 type="submit"
        | 取得
ul
  li
    | 指定した期間、証券コードの株価データについて、日足の調整後終値を取得します。
  li
    | 期間を指定しない場合、直近1ヶ月分のデータを取得します。
  li
    | 目安として、1つの証券コード4年分の取得につき約1分かかります。(通信状況によってさらに遅くなる場合もあります。)
br